name: Generate LaTeX Resume
'on':
  push:
    branches:
      - main
  workflow_dispatch:
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: Drish_Resume.tex
      - name: Upload PDF file as artifact
        uses: actions/upload-artifact@v4
        with:
          name: Drish_Resume
          path: Drish_Resume.pdf

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      - name: Download artifact (Resume PDF)
        uses: actions/download-artifact@v4
        with:
          name: Drish_Resume
      - name: Set Git identity
        run: |
          git config --global user.email "${{ secrets.EMAIL }}"
          git config --global user.name "${{ secrets.NAME	}}"

      - name: Delete live branch if it exists
        run: |
          git fetch origin
          if git ls-remote --exit-code --heads origin live; then
            git push origin --delete live
          fi

      - name: Create or update live branch with resume
        run: |
          git checkout --orphan live
          git rm -rf .  # Clean the working directory
          git checkout ${{ github.sha }} Drish_Resume.pdf  
          git add Drish_Resume.pdf
          git commit -m "Update PDF"
          git push --force origin live 
        
  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      - name: Download artifact (Resume PDF)
        uses: actions/download-artifact@v4
        with:
          name: Drish_Resume
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          files: Drish_Resume.pdf
          body: Drish | Resume
